"""Module Communication Protocol — standardize how workflow modules talk to each other.

Layer 2 of the "text is intelligence" design (§1 Idea 2 of DESIGN_RATIONALE):
every End/Answer node output SHOULD conform to this envelope so downstream
modules can reliably extract structured data while preserving natural language.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ModuleOutput(BaseModel):
    """Standard envelope for all workflow module outputs.

    When a non-empty *envelope* dict is present in an End node's outputs,
    downstream blocks can trust that ``result``, ``structured``, ``context``,
    ``module_name`` and ``version`` are always available — even if the
    workflow author used plain Template or LLM blocks.

    Usage in an End node config::

        {"outputs": {
            "envelope": {
                "result":       {"$ref": {"node_id": "llm", "path": ["text"]}},
                "structured":   {"$ref": {"node_id": "extractor", "path": ["structured"]}},
                "context":      "Generated by data_analyzer v1",
                "module_name":  "data_analyzer",
                "version":      1,
            }
        }}
    """

    result: Any = Field(
        default="",
        description="Primary natural-language output. LLM-readable summary.",
    )
    structured: dict[str, Any] | None = Field(
        default=None,
        description="Machine-parseable key-value data for deterministic routing.",
    )
    context: str = Field(
        default="",
        description="Human-readable context about how this output was produced.",
    )
    module_name: str = Field(default="")
    version: int = Field(default=1, ge=0)


def wrap_module_output(
    result: Any,
    *,
    structured: dict[str, Any] | None = None,
    context: str = "",
    module_name: str = "",
    version: int = 1,
) -> dict[str, Any]:
    """Build a standard module output envelope dict."""
    return ModuleOutput(
        result=result,
        structured=structured,
        context=context,
        module_name=module_name,
        version=version,
    ).model_dump(mode="json", exclude_none=True)


def is_envelope(value: Any) -> bool:
    """Return True if *value* looks like a ModuleOutput envelope."""
    if not isinstance(value, dict):
        return False
    return "result" in value and (
        "module_name" in value or "structured" in value
    )


def extract_from_envelope(value: dict[str, Any], key: str) -> Any:
    """Safely extract a field from a module output envelope."""
    if not is_envelope(value):
        return None
    return value.get(key)
